version: "0.2"
language: en
caseSensitive: true
ignorePaths:
  - "*.cassette"
  - "go.sum"
  - "go.mod"
  - "node_modules/**"
  - ".git/**"
  - "tmp/**"
  - "bin/**"
  - "coverage.txt"
words:
  # Project specific
  - htmltest
  - refcache
  - htmldoc
  # Go packages/libraries
  - badoux
  - govcr
  - mergo
  - docopt
  - daviddengcn
  - imdario
  - seborama
  - wjdp
  # HTML/testing terms
  - favicon
  - opengraph
  - proofer
  - checkmail
  # Other
  - github
  - ints
  - preconnect
  - rels