version: "0.2"
language: en
caseSensitive: true
ignorePaths:
  - "*.cassette"
  - go.sum
  - go.mod
  - node_modules/**
  - .git/**
  - tmp/**
  - bin/**
  - coverage.txt
words:
  - badoux
  - chalin
  - checkmail
  - daviddengcn
  - docopt
  - favicon
  - github
  - govcr
  - htmldoc
  - htmlproofer
  - htmltest
  - imdario
  - ints
  - lastmod
  - mergo
  - opengraph
  - preconnect
  - proofer
  - refcache
  - regexs
  - rels
  - seborama
  - stretchr
  - wjdp
